### PR TITLE
fix: Navigation with GoRouter reorganized

### PR DESCRIPTION
**Pull request by jonas-martinez**
#__ 

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

### CODE REVIEW

**Comment by jonas-martinez** [comment]
Blocked as long as CommonNavigator defines routes starting with "/".

**Comment by jonas-martinez** [comment]
Looks good now. It seems to be working properly

**Review by taorepoara — APPROVED** [review]
Seems OK

**Pull request merged**
