### PR TITLE
ci: Update flutter version

### PR DESCRIPTION
**Pull request by jonas-martinez**
## Description of the changes
The CI was not working, I suppose because of the flutter version which should be 3.10.x but was 3.7.x on the actions.

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [x] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by jonas-martinez** [comment]
We'll see on Monday with @taorepoara

**Review by taorepoara — APPROVED** [review]
Seems good to me

**Review by shiipou — APPROVED** [review]

**Pull request merged**
